name: CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone --depth=1 "https://github.com/${GITHUB_REPOSITORY}.git" .
      - name: Show runtime
        run: node --version && npm --version
      - run: npm run check
      - run: npm run demo
      - run: npm pack --dry-run
